name: mobile
description: "Desafio Pago App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔥 FIREBASE
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0

  # 🔥 LOGIN GOOGLE
  google_sign_in: ^7.2.0

  # 🔥 STORAGE (UPLOAD DE IMAGEM/VÍDEO)
  firebase_storage: ^12.3.0

  # 🔥 IMAGE PICKER
  image_picker: ^1.1.2

  # 🔥 UUID (IMPORTANTE PRO DESAFIO)
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png